name: ft_irc CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Tests
        run: make test

      - name: Execute Unit Tests
        run: ./irc_tests