name: ft_irc CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Tests
        run: make test

      - name: Execute Unit Tests
        run: ./irc_tests

  build-and-test:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Compile Server
      run: make
    
    - name: Start IRC Server in background
      run: ./ircserv 6667 testpass &
      
    - name: Wait for server to boot
      run: sleep 1
    
    - name: Run Integration Tests
      run: python3 test/commands_tests/test_handshake.py